# Generated by Django 5.2.7 on 2025-10-28 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_eventcard_fearcard_invadercard_gameevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventcard",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="eventcard",
            name="image_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="eventcard",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="fearcard",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="fearcard",
            name="image_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="fearcard",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
