# Generated by Django 5.2.7 on 2025-10-28 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_eventcard_description_eventcard_image_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fearcard",
            name="stage_one",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="fearcard",
            name="stage_three",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="fearcard",
            name="stage_two",
            field=models.TextField(blank=True),
        ),
    ]
