# Generated by Django 5.2.7 on 2025-10-28 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_fearcard_stage_one_fearcard_stage_three_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameevent",
            name="terror_level",
            field=models.CharField(
                choices=[
                    ("1", "Terror Level 1"),
                    ("2", "Terror Level 2"),
                    ("3", "Terror Level 3"),
                ],
                max_length=3,
                null=True,
            ),
        ),
    ]
