# Generated by Django 5.2.7 on 2025-10-28 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_gameevent_terror_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fearcard",
            name="image_url",
        ),
        migrations.AddField(
            model_name="fearcard",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="fear_cards/"),
        ),
    ]
