from game.models import EventCard

event_cards = [
  "Cultural Assimilation",
  "Distant Exploration",
  "Farmers Seek the Dahan for Aid",
  "Heavy Farming",
  "Interesting Discoveries",
  "Invaders Surge Inland",
  "Investigation of Dangers",
  "Missionaries Arrive",
  "New Species Spread",
  "Population Rises",
  "Promising Farmland",
  "Putting Down Roots",
  "Rising Interest in the Island",
  "Sacred Sites Under Threat",
  "Search for New Lands",
  "Seeking the Interior",
  "Slave Rebellion",
  "Strange Tales Attract Explorers",
  "Tight-Knit Communities",
  "Urban Development",
  "Wave of Reconnaissance",
  "Well-Prepared Explorers",
  "Years of Little Rain",
  "Bureaucrats Adjust Funding",
  "Cities Rise",
  "Civic Engagement",
  "Coastal Towns Multiply",
  "Dahan Trade with the Invaders",
  "Eager Explorers",
  "Fortune-Seekers",
  "Gradual Corruption",
  "Hard-Working Settlers",
  "Harvest Bounty, Harvest Dust",
  "Invested Aristocracy",
  "Lesser Spirits Imperiled",
  "Life's Balance Tilts",
  "Mapmakers Chart the Wild",
  "No Bravery Without Numbers",
  "Numinous Crisis",
  "Overconfidence",
  "Provincial Seat",
  "Pull Together in Adversity",
  "Relentless Optimism",
  "Remnants of a Spirit's Heart",
  "Resourceful Populace",
  "Seek New Farmland",
  "Smaller Ports Spring Up",
  "Sprawl Contained by the Wilds",
  "Temporary Truce",
  "The Frontier Calls",
  "The Struggles of Growth",
  "Thriving Trade",
  "Wounded Lands Attract Explorers",
  "Accumulated Devastation",
  "An Ominous Dawn",
  "Ethereal Conjunction",
  "Far-off Wars Touch the Island",
  "Focused Farming",
  "Influx of Settlers",
  "Search for Unclaimed Land",
  "Terror Spikes Upwards",
  "Visions Out of Time",
  "A Strange Madness Among the Beasts",
  "Outpaced",
  "War Touches the Island's Shores",
  "Far-off Wars Touch the Island"
]

for name in event_cards:
    EventCard.objects.get_or_create(name=name)
