from game.models import FearCard

fear_cards = [
  "Avoid the Dahan",
  "Belief Takes Root",
  "Dahan Enheartened",
  "Dahan on their Guard",
  "Dahan Raid",
  "Emigration Accelerates",
  "Fear of the Unseen",
  "Isolation",
  "Overseas Trade Seems Safer",
  "Retreat!",
  "Scapegoats",
  "Seek Safety",
  "Tall Tales of Savagery",
  "Trade Suffers",
  "Wary of the Interior",
  "Dahan Attack",
  "Dahan Threaten",
  "Demoralized",
  "Depart the Dangerous Land",
  "Discord",
  "Explorers are Reluctant",
  "Flee the Pestilent Land",
  "Immigration Slows",
  "Panic",
  "Panicked by Wild Beasts",
  "Plan for Departure",
  "Quarantine",
  "Too Many Monsters",
  "Tread Carefully",
  "Unrest",
  "Beset by Many Troubles",
  "Dahan Reclaim Fishing Grounds",
  "Flee from Dangerous Lands",
  "Nerves Fray",
  "Sense of Dread",
  "Theological Strife",
  "Angry Mobs",
  "Communities in Disarray",
  "Depopulation",
  "Mimic the Dahan",
  "Spreading Timidity",
  "Civil Unrest",
  "Dahan Gain the Edge",
  "Daunted by the Dahan",
  "Distracted by Local Troubles",
  "Restlessness",
  "Seek Company",
  "Struggles over Farmland",
  "Supply Chains Abandoned",
  "Unsettled"
]

for name in fear_cards:
    FearCard.objects.get_or_create(name=name)
